CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text not null unique,
    pass text not null,
    score integer DEFAULT 0,
    savegame text DEFAULT ''
);